### ISSUE TITLE
TS Issues - Why do I need to defines the props as undefined

### ISSUE THREAD

**Issue by JesJehle** [sumo-rhine/kinamo#58]
https://github.com/sumo-rhine/kinamo/blob/4a5b23c0b411f66ee06cf19c3021a194df5b27a2/src/pages/CityPage.tsx#L47-L47

**Comment by mmaelicke** [comment]
because city can be undefined or null:
https://github.com/sumo-rhine/kinamo/blob/4a5b23c0b411f66ee06cf19c3021a194df5b27a2/src/pages/CityPage.tsx#L35
and
https://github.com/sumo-rhine/kinamo/blob/4a5b23c0b411f66ee06cf19c3021a194df5b27a2/src/pages/CityPage.tsx#L20

The reason is, that the data comes in via Promises, thus the rendering can occur while data has not yet arrived. Additionally, on mid term we should change the definition as explained in #54, as the user might request a cityId that does actually not exist.

**Comment by JesJehle** [comment]
Thanks! You are too fast :)
